### ISSUE TITLE
The solution is not working with apps using HammerJS

### ISSUE THREAD

**Issue by barna-n** [Stanza987/angular-universal-firebase#1]
Hi Stanley!
I can't use this method to deploy A5 apps to Firebase with SSR because my app is using the HammerJS lib and Angular Material.
The following error occurs during deployment if I use HammerJS:

Error: Error occurred while parsing your function triggers.
ReferenceError: window is not defined
    at Object.<anonymous> (/private/var/folders/7c/78msd3tj5zj75g1_pbnmpf7m0000gn/T/fbfn_7305dKGJirWMAoKm/node_modules/hammerjs/hammer.js:2643:4)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.LYNW (/private/var/folders/7c/78msd3tj5zj75g1_pbnmpf7m0000gn/T/fbfn_7305dKGJirWMAoKm/dist-server/main.bundle.js:1:40603)
    at l (/private/var/folders/7c/78msd3tj5zj75g1_pbnmpf7m0000gn/T/fbfn_7305dKGJirWMAoKm/dist-server/main.bundle.js:1:220)

Have you got any solution for this?

Kind rgds,
Barna

**Comment by barna-n** [comment]
https://github.com/hammerjs/hammer.js/issues/1060
