### ISSUE TITLE
Followed the docs but I got the below error

### ISSUE THREAD

**Issue by davidmontgom** [Stanza987/angular-universal-firebase#4]
/angular-universal-firebase/functions/index.js:12
const functions = require('firebase-functions');
                                              ^
SyntaxError: Identifier 'functions' has already been declared
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:18:11
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:38:3)

**Comment by davidmontgom** [comment]
resolved it works
